### ISSUE TITLE
Floating point issue

### ISSUE THREAD

**Issue by 2020karaulov2020** [undnull/refraction#6]
https://github.com/undnull/refraction/blob/df5103320f01559b4df3c19781fd28a9ceac796c/src/tools/vrad_dll/vrad_dispcoll.cpp#L868

from cfloat 

![bB4NMr 1](https://user-images.githubusercontent.com/62130676/128557111-c1f5d3dc-dc39-47f4-8b00-c2ee631bdb93.jpg)

**Need use -FLT_MAX**

**Comment by undnull** [comment]
The initialization of the vector doesn't make any sense and won't make any since both `vecMin` and `vecMax` are refilled in the following double-depth `for` loop.

**Comment by undnull** [comment]
See, there are three elements of each vector, and...
```cpp
    for ( int iPoint = 0; iPoint < 4; ++iPoint )
    {
        for ( int iAxis = 0; iAxis < 3; ++iAxis )
        {
            vecMin[iAxis] = min( vecMin[iAxis], pPoints[iPoint][iAxis] );
            vecMax[iAxis] = max( vecMax[iAxis], pPoints[iPoint][iAxis] );
        }
    }
```
