### ISSUE TITLE
True floating point issue

### ISSUE THREAD

**Issue by 2020karaulov2020** [undnull/refraction#7]
https://github.com/undnull/refraction/blob/0c9a8bcd2f1144e5bd97e419a171359ae42575e4/src/game/client/c_effects.cpp#L1670
filled in
https://github.com/undnull/refraction/blob/0c9a8bcd2f1144e5bd97e419a171359ae42575e4/src/game/client/c_effects.cpp#L1772

BUT FLT_MIN is
![128557111-c1f5d3dc-dc39-47f4-8b00-c2ee631bdb93 1](https://user-images.githubusercontent.com/62130676/128587958-f49c4c9f-7068-4fa4-997c-672a083600e4.jpg)

Need use -FLT_MAX

**Comment by undnull** [comment]
Logically speaking `min` value should be set to maximum when the minimal value is calculated. Hence the `max` value need to be set to the minimum when the maximal value is calculated. I again don't see any troubles here.  
¯\\\_(ツ)\_/¯
